/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    mavenCentral()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api(libs.org.openrewrite.rewrite.templating)
    api(libs.javax.annotation.javax.annotation.api)
    api(libs.org.openrewrite.meta.rewrite.analysis)
    api(libs.org.openrewrite.rewrite.java)
    api(libs.org.openrewrite.rewrite.yaml)
    api(libs.org.openrewrite.rewrite.xml)
    api(libs.org.openrewrite.recipe.rewrite.java.dependencies)
    testImplementation(libs.org.openrewrite.rewrite.test)
//    testImplementation(libs.org.junit.jupiter.junit.jupiter)
    testImplementation(libs.org.assertj.assertj.core)
    testImplementation(libs.com.google.guava.guava)
    testImplementation(libs.org.apache.commons.commons.lang3)
//    testImplementation(libs.org.springframework.spring.core)
//    testImplementation(libs.org.springframework.spring.context)
//    testAnnotationProcessor("org.projectlombok:lombok")         // <-- critical
    compileOnly(libs.org.projectlombok.lombok)
    implementation(libs.org.projectlombok.lombok)
//    annotationProcessor("org.projectlombok:lombok")         // <-- critical
    compileOnly(libs.com.google.errorprone.error.prone.core)
    compileOnly(libs.org.openrewrite.rewrite.java.v17)
    compileOnly(libs.org.openrewrite.rewrite.java.v21)
    compileOnly(libs.org.openrewrite.rewrite.java.v25)
}

group = "com.tazzledazzle"
version = "0.1.0-SNAPSHOT"
description = "rewrite-recipe-starter"
java.sourceCompatibility = JavaVersion.VERSION_21

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
